version: '2'
services:
  ubuntu:
    container_name: ubuntu
    build: ./ubuntu
    environment:
      - TZ=Asia/Tokyo
    networks:
      net:
        ipv4_address: 172.20.0.10
    privileged: true
    stdin_open: true
    tty: true

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
